apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  name: demo-bucket-crossplane
  namespace: default   # 🔥 MUST EXIST
spec:
  forProvider:
    region: us-east-1
  providerConfigRef:
    name: default
