apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  name: demo-bucket-crossplane
  annotations:
    crossplane.io/external-name: demo-bucket-crossplane-12345
spec:
  forProvider:
    region: us-east-1
  providerConfigRef:
    name: default
