apiVersion: eks.aws.upbound.io/v1beta1
kind: Cluster
metadata:
  name: eks-test
  namespace: crossplane-system
  labels:
    cluster: eks-test
spec:
  forProvider:
    region: us-east-1
    version: "1.29"
    roleArnSelector:
      matchLabels:
        cluster: eks-test
    vpcConfig:
      - subnetIdSelector:
          matchLabels:
            cluster: eks-test
        endpointPublicAccess: true
        endpointPrivateAccess: false
    tags:
      purpose: eks-test
      env: test
  providerConfigRef:
    name: default
