apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  name: eks-test-cluster-role
  namespace: crossplane-system
  labels:
    cluster: eks-test
spec:
  forProvider:
    assumeRolePolicyDocument: |
      {
        "Version": "2012-10-17",
        "Statement": [{
          "Effect": "Allow",
          "Principal": {"Service": "eks.amazonaws.com"},
          "Action": "sts:AssumeRole"
        }]
      }
    tags:
      - key: purpose
        value: eks-test
  providerConfigRef:
    name: default
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: eks-test-cluster-policy
  namespace: crossplane-system
spec:
  forProvider:
    policyArn: arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
    roleSelector:
      matchLabels:
        cluster: eks-test
  providerConfigRef:
    name: default
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  name: eks-test-node-role
  namespace: crossplane-system
  labels:
    nodegroup: eks-test
spec:
  forProvider:
    assumeRolePolicyDocument: |
      {
        "Version": "2012-10-17",
        "Statement": [{
          "Effect": "Allow",
          "Principal": {"Service": "ec2.amazonaws.com"},
          "Action": "sts:AssumeRole"
        }]
      }
    tags:
      - key: purpose
        value: eks-test
  providerConfigRef:
    name: default
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: eks-test-node-policy
  namespace: crossplane-system
spec:
  forProvider:
    policyArn: arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
    roleSelector:
      matchLabels:
        nodegroup: eks-test
  providerConfigRef:
    name: default
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: eks-test-cni-policy
  namespace: crossplane-system
spec:
  forProvider:
    policyArn: arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
    roleSelector:
      matchLabels:
        nodegroup: eks-test
  providerConfigRef:
    name: default
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: eks-test-ecr-policy
  namespace: crossplane-system
spec:
  forProvider:
    policyArn: arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
    roleSelector:
      matchLabels:
        nodegroup: eks-test
  providerConfigRef:
    name: default
