apiVersion: ec2.aws.upbound.io/v1beta1
kind: InternetGateway
metadata:
  name: eks-test-igw
  namespace: crossplane-system
  labels:
    cluster: eks-test
spec:
  forProvider:
    region: us-east-1
    vpcIdSelector:
      matchLabels:
        cluster: eks-test
    tags:
      Name: eks-test-igw
  providerConfigRef:
    name: default
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: RouteTable
metadata:
  name: eks-test-rt
  namespace: crossplane-system
  labels:
    cluster: eks-test
spec:
  forProvider:
    region: us-east-1
    vpcIdSelector:
      matchLabels:
        cluster: eks-test
    tags:
      Name: eks-test-rt
  providerConfigRef:
    name: default
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Route
metadata:
  name: eks-test-default-route
  namespace: crossplane-system
spec:
  forProvider:
    region: us-east-1
    destinationCidrBlock: 0.0.0.0/0
    routeTableIdSelector:
      matchLabels:
        cluster: eks-test
    gatewayIdSelector:
      matchLabels:
        cluster: eks-test
  providerConfigRef:
    name: default
