apiVersion: eks.aws.upbound.io/v1beta1
kind: NodeGroup
metadata:
  name: eks-test-ng
  namespace: crossplane-system
spec:
  forProvider:
    region: us-east-1
    clusterNameSelector:
      matchLabels:
        cluster: eks-test
    nodeRoleArnSelector:
      matchLabels:
        nodegroup: eks-test
    subnetIdSelector:
      matchLabels:
        cluster: eks-test
    instanceTypes:
      - t3.small
    scalingConfig:
      - minSize: 1
        maxSize: 2
        desiredSize: 1
    updateConfig:
      - maxUnavailable: 1
    tags:
      purpose: eks-test
      env: test
  providerConfigRef:
    name: default
