apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  name: eks-test-subnet-a
  namespace: crossplane-system
  labels:
    cluster: eks-test
spec:
  forProvider:
    region: us-east-1
    availabilityZone: us-east-1a
    cidrBlock: 10.0.1.0/24
    mapPublicIpOnLaunch: true
    vpcIdSelector:
      matchLabels:
        cluster: eks-test
    tags:
      Name: eks-test-subnet-a
      kubernetes.io/role/elb: "1"
  providerConfigRef:
    name: default
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  name: eks-test-subnet-b
  namespace: crossplane-system
  labels:
    cluster: eks-test
spec:
  forProvider:
    region: us-east-1
    availabilityZone: us-east-1b
    cidrBlock: 10.0.2.0/24
    mapPublicIpOnLaunch: true
    vpcIdSelector:
      matchLabels:
        cluster: eks-test
    tags:
      Name: eks-test-subnet-b
      kubernetes.io/role/elb: "1"
  providerConfigRef:
    name: default
