apiVersion: v1
kind: ConfigMap
metadata:
  name: gitops-tool-nginx-conf
  namespace: default
  labels:
    app: gitops-tool
data:
  default.conf: |
    server {
        listen 80;
        server_name _;

        root /usr/share/nginx/html;
        index index.html;

        auth_basic "GitOps Tool";
        auth_basic_user_file /etc/nginx/auth/.htpasswd;

        location / {
            try_files $uri $uri/ /index.html;
        }
    }
