apiVersion: v1
kind: Secret
metadata:
  name: gitops-tool-auth
  namespace: default
  labels:
    app: gitops-tool
type: Opaque
stringData:
  .htpasswd: |
    demo:$apr1$XSL9eMgS$m2tSGyZNUTVQMQ1uGYbfx.
    admin:$apr1$vtzXB0KP$IFCcSj2TP/Tdbe/NUqTob.
