apiVersion: v1
kind: Service
metadata:
  name: gitops-tool
  namespace: default
  labels:
    app: gitops-tool
spec:
  type: NodePort
  selector:
    app: gitops-tool
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP
